server:
  port: 30000
spring:
  application:
    name: gulimall-thirdparty
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: a5ec06bd-f15a-49e5-ab15-a360e9b8f9a1
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    include: aliyunTest

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

